GET http://localhost:5000/getUsers
Content-Type: application/json

###
// LOGIN
POST  http://localhost:5000/login
Content-Type: application/json

{
    "username": "sa",
    "password": "123"
}

###
// getme
GET http://localhost:5000/GetMe
Content-Type: application/json

###
//logout
DELETE http://localhost:5000/logout
Content-Type: application/json

###
// getSuratJalan
POST  http://localhost:5000/getSuratJalan
Content-Type: application/json

{
    "pageNumber": 0,
    "pageSize": 10,
    "kriteria": "",
    "filterValue": ""
}
