GET http://localhost:5000/getUsers
Content-Type: application/json

###
// LOGIN
POST  http://localhost:5000/login
Content-Type: application/json

{
    "username": "sa",
    "password": "123"
}

###
// getme
GET http://localhost:5000/GetMe
Content-Type: application/json

###
//logout
DELETE http://localhost:5000/logout
Content-Type: application/json

###
// getSuratJalan
GET http://localhost:5000/getSuratJalan/1/10
Content-Type: application/json
